Handle SQL Injection
VahidFarahmandian/spoota-internship-roadmap pull request #8
Opened 2024-03-01 21:50 UTC by HosseinDinarvand

I apply bellow changes:
1) add .gitignore file
2) update middle pipline in program.cs
3) change folder structure
4) apply another changes

2024-03-01 23:23 UTC, VahidFarahmandian commented
> I apply bellow changes:
> 
> 1. add .gitignore file
> 2. update middle pipline in program.cs
> 3. change folder structure
> 4. apply another changes

@HosseinDinarvand you have placed gitignore file in the root of the repository which will effect other folders that you do not own. You should move it to your own folder so that it will effect only your files/folders.

2024-03-01 23:26 UTC, VahidFarahmandian commented
If you are opening a PR regarding an issue or set of issues, you need to specify them in Development section if the PR. 
I did it for you and you can check it.

2024-03-01 23:49 UTC, HosseinDinarvand commented
> > I apply bellow changes:
> > 
> > 1. add .gitignore file
> > 2. update middle pipline in program.cs
> > 3. change folder structure
> > 4. apply another changes
> 
> @HosseinDinarvand you have placed gitignore file in the root of the repository which will effect other folders that you do not own. You should move it to your own folder so that it will effect only your files/folders.


OK, I will add .gitignore in my own folder and push again.

2024-03-02 00:32 UTC, HosseinDinarvand commented
> If you are opening a PR regarding an issue or set of issues, you need to specify them in Development section of the PR. I did it for you and you can check it.

Ok,I will follow this recommendation in the next issues.
thank's for your help.

2024-03-03 14:47 UTC, VahidFarahmandian requested changes
gitignore :-|

2024-03-03 17:49 UTC, VahidFarahmandian requested changes

2024-03-03 17:49 UTC, VahidFarahmandian commented on .gitignore
this file should be removed.

2024-03-03 20:19 UTC, HosseinDinarvand commented
I add **MsTest** project for ConsoleApp by using **Moq package** in last commit, please check my code.

2024-03-03 21:59 UTC, VahidFarahmandian approved these changes

2024-03-03 21:59 UTC, merged